### ISSUE TITLE
where to find "source("../grapevine/generate_figures/functions.R")" file?

### ISSUE THREAD

**Issue by liamxg** [SarahNadeau/cov-swiss-phylo#1]

**Comment by SarahNadeau** [comment]
The grapevine repo referenced is here: https://github.com/cevo-public/Grapevine-SARS-CoV-2-Introduction-Analysis. I added that information to the README, thanks for pointing out the omission.

**Comment by liamxg** [comment]
@SarahNadeau @LiXingguangBrandonStark thanks.

**Comment by liamxg** [comment]
<img width="953" alt="image" src="https://user-images.githubusercontent.com/46078579/200825191-f2aa89a4-bf8a-4e49-a67f-01f79aa1921b.png">

**Comment by liamxg** [comment]
@SarahNadeau could you please tell me how to find the log files, thanks.
